---
title: "Project 4: Identifying the Taxonomy of a Bacterial Secondary Infection in COVID-19 Patients"
format: html
---

**General guidance for project**

Recommended number of participants per group: 4 to 6.

Project work running time: 1.5h, on Friday.

Each group will present their work in max 7 minutes, with 3 minutes left for question. Each member of the group would be expected to present at least one slide.

## **Case Scenario**

During the COVID-19 pandemic, additional investigations on the nasal microbiome of SARS-CoV-2 positive patients were conducted at your facility to better understand possible secondary bacterial infections associated with disease progression. Among the collected samples, one patient exhibited a dominant bacterial isolate recovered from a nasal swab culture. Due to the potential clinical significance of bacterial co-infections in COVID-19 patients, the isolate was subjected to whole genome sequencing using Illumina paired-end sequencing technology. Insert size estimate was 150 bp before sequencing, 

As a bioinformatics analyst in the laboratory, the task is to process the sequencing data, assemble the bacterial genome, evaluate the quality of the assembly, and determine the taxonomic identity of the isolate. Correct identification of the organism is important for understanding possible secondary infections and their implications in patient management and antimicrobial surveillance.

## **Learning Objectives**

At the end of this exercise, participants should be able to:

-   Assemble a bacterial genome from Illumina paired-end sequencing reads

-   Evaluate and interpret genome assembly statistics

-   Identify bacterial taxa using sequence similarity searches

-   Interpret results within the context of secondary bacterial infection

## Data download

Sequencing data consists of cleaned Illumina paired-end reads generated from a bacterial isolate recovered from a COVID-19 positive patient. Download the dataset using the provided link in the data directory: <https://ln.run/G8con>

Files included:

\- Isolate_1.fastq.gz

\- Isolate_2.fastq.gz

## Tools to be used

-   Velvet

-   Assembly-stats

-   Seqtk

-   Blastn

## Tasks

**Task 1 - Genome Assembly** 

-   Try odd-numbered k-mer lengths between 71 and 99 (e.g., 71, 81, 91, and 99).

-   Try also k-mer length 31, for comparison with the ones above.

**Task 2 - Assembly Assessment**

**Task 3 - Taxonomic Identification Using BLASTn**

-   Open the assembled contigs file

-   Select a long sequence.

-   Copy the FASTA sequence.

-   Open the NCBI BLAST website (https://www.ncbi.nlm.nih.gov/geo/query/blast.html). 

-   Use BLASTn against the nucleotide database.

-   Record the top matches.

**Guide Questions**

1.  Determine the total assembly size of the bacterial genome.

2.  Determine the total number of contigs generated.

3.  Identify the N50 value of the assembly.

4.  Does the assembly size appear reasonable for a bacterial genome?

5.  Is the assembly fragmented or relatively contiguous?

6.  What might affect assembly quality?

7.  Which assembly would you choose as the final assembly and why?

8.  What is the most likely taxonomic identity of the isolate?

9.  Does the identified organism have known associations with respiratory or opportunistic infections?
