---
title: "Project 5: QC Project evaluation of a novel sequencing platform"
format: html
---

**General guidance for project**

Recommended number of participants per group: 4 to 6.

Project work running time: 1.5h, on Friday.

Each group will present their work, in their respective classroom. Each member of the group would be expected to present at least one slide.

## **Introduction**

Your research institute has just acquired a new Illumina sequencing machine and they have recently performed their first sequencing run. As you are the only person in your institute that has attended an NGS course and have the skills to analyse NGS data, the head of your department has volunteered you to analyse the data and present your findings to the head of the institute. The sequencing data consists of 2 lanes of Illumina data for two Salmonella Paratyphi B isolates and your task is to download the sequencing data for the run, QC and analyse it. Prepare a short presentationfor the head of the institute describing the results of your analyses. 

## **Download sequencing data**

Download the sequencing data from Github:

<https://github.com/WCSCourses/Genome-Sequence-Analysis-Standardised-Resources/tree/main/course_modules/Projects/project5/data>

## Download the FASTA

`wget -O CP000886.fasta  "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=CP000886&rettype=fasta&retmode=text"`

## **Tools to be used**

-   [Bwa mem](https://bio-bwa.sourceforge.net/bwa.shtml)

-   [Samtools stats](https://www.htslib.org/doc/samtools-stats.html)

-   Bcftools 

## **Tasks**

Use your knowledge from the QC, alignment and variant calling modules. 

**Task 1**: Align the reads to the reference genome with bwa mem for each group.

**Task 2**: Collect the statistics about the alignments (‘samtools stats’ command) and produce QC plots? Can you spot any problems in the QC plots?

**Task 3**: Call variants with bcftools to produce a VCF file (\~5 min per group)

1.  Filter variants that pass QUAL\>=30 and DP\>=20.

2.  What is the number of SNPs, indels and TS/TV before and after filtering in Group2 and Group4 samples?

3.  Can you draw any conclusions about the first sequencing run. Was it a success? Should the institute keep the sequencing instrument? What are your recommendations moving forward.
