---
title: "Project 3:  Identifying host genetic factors for resistance to SARS-CoV"
format: html
---

In this project, you'll look for genetic mutations that make mice more or less susceptible to COVID-like infection. By the end, you'll understand how to:

-   Extract variants from genomic databases

-   Interpret what variants do to proteins

-   Link genetic changes to disease risk

**Background: Why this matters?**

Humans get COVID at different severity levels. Some people barely get sick; others get severe disease. Part of this comes from **host genetics**—variations in our DNA that affect how our immune system fights the virus.

To study this safely, researchers use mice. Different mouse strains (like different ethnic backgrounds in humans, but more extreme) respond very differently to SARS-CoV:

-   **NOD/ShiLtJ**: Resistant, barely gets sick

-   **A/J, C57BL/6J**: Moderate disease, recovers fine

-   **CAST/EiJ, PWK/PhJ, WSB/EiJ**: Severe disease, lose weight, sometimes die

Researchers found **four major genomic regions** (called QTLs) linked to disease severity. In this project, you will focus specifically on the HrS1 locus and characterize genetic variants within Trim55 across 52 inbred mouse strains to identify candidate mutations which could be driving susceptibility or resistance SARS-CoV infection.

**References**

Genome Wide Identification of SARS-CoV Susceptibility Loci Using the Collaborative Cross

<https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005504> 

## Data download

1.  Open the Firefox browser in the VM

2.  Download VCF with SNPs and indels of the 52 mouse strains. (Note: The full VCF is available from the European Variation Archive under PRJEB43298. However, the VCF file for the whole genome is very large. In this project, we will only focus on chromosome 3, which can be downloaded <https://drive.google.com/file/d/1dNfcO49nov0MzA2UIuOStJIlc1y_oZ3w/view?usp=sharing>

**Explanation:** You can download the files manually through the Firefox browser in the VM and move it to project folder. Alternatively, you can download using wget like this

**`# Create project directory`**`mkdir $HOME/Project3 && cd "$_"`

**`# Download the VCF directly from Google Drive`**

`wget -O "mgp_REL2005_snps_indels.3.18000000-22000000.vcf.gz" "https://drive.google.com/uc?export=download&id=1dNfcO49nov0MzA2UIuOStJIlc1y_oZ3w"`

## Tasks

**Task 1:** Confirm that you have 52 samples (i.e. strains) in this VCF. Extract the SNP and indel variants in the Trim55 gene into another VCF file

**Task 2** Identify variants that are most likely to affect the function of the gene.

Hint:

-   Print the CSQ at position 3:19671000 to understand more about the variant. 

-   Repeat again for position 3:19694085. Can you explain this? 

-   Hint: comma in the CSQ field?

**Task 3 (optional)**: Tabulate the different CSQ predictions (Consequence\|Impact\|Symbol) and their counts. There should be a total of 4659 CSQ predictions.

Hint: 

-   you can use sed ‘s/,/\\n/g’ to replace comma (,) in the CSQ field with a new line character (\\n) (i.e. start a new line whenever there is comma in the CSQ field)

-   then capture the column that you are interested in using cut command, then explore the CSQ type of interest

-   Here is a guide which describes the CSQ annotations of the variants: <https://m.ensembl.org/info/genome/variation/prediction/predicted_data.html> 

**Task 4:** Most variants are harmless (intronic, downstream). We want to focus on the ones that change proteins (missense). Find **only** the missense variants present in Trim55 and save into a text file. There should be 11 such variants.

**Task 5:** Find the strains that have missense mutations in the Trim55 gene. Ths gives you a clue to find potential mutations in Trim55 that may mediate response to SARS-CoV pathogenesis in mice.

## Recommended tools

-   bcftools view

-   bcftools query

-   Interproscan, or any other tools that let you explore structures and function of proteins (optional)
